### ISSUE TITLE
__init__ error: more arguments given than it takes

### ISSUE THREAD

**Issue by twothreenine** [twothreenine/kerndlware#2]
When you try to access one of those:
http://127.0.0.1:8000/account
http://127.0.0.1:8000/admin/core/currency/
http://127.0.0.1:8000/admin/core/moneybox/
a type error appears.
I defined custom init-methods for models currency and moneybox, currency init is the one that "takes from 2 to 6 positional arguments but 7 were given", moneybox init "takes from 2 to 3 positional arguments but 4 were given". I did that in order to create money-box-stocks for all combinations of currency and money-box. Whenever a new currency is created, a money-box-stock for every money-box shall be created, and vice versa.
I have no idea where 7 resp. 4 arguments are given to create a currency resp. a moneybox.

**Comment by twothreenine** [comment]
Import_scripts\ods.py: (former "transactions.py")
Special characters like umlaute and ß are ignored with open(errors='ignore'), how can we read them?

**Comment by twothreenine** [comment]
Import_scripts\ods.py import_transactions:
In order to import transactions like cost-sharing, proceeds-sharing etc properly, we have to consider that some accounts may have been excluded from the transaction. We have to detect whether the next row in the CSV is of type 9 (exception) resp. how many of the following rows are of type 9, then read their account id and exclude the account from the participating accounts field of the transaction.
I don't know what this line means: "for index,row in enumerate(reader):"
what about the comma between index and row, what does it mean?

**Comment by Zepp10x** [comment]
> Django expects the signature of a model's constructor to be (self, *args, **kwargs), or some reasonable facsimile. Your changing the signature to something completely incompatible has broken it.
> *http://stackoverflow.com/a/843669/3144403*

Try to use a class method called `create` for creating new instances of model classes: http://stackoverflow.com/a/843740/3144403

If you continue to have problems, I can take a closer look at it.
