### ISSUE TITLE
Import scripts: exclusions for share-transactions

### ISSUE THREAD

**Issue by twothreenine** [twothreenine/kerndlware#4]
Import_scripts\ods.py import_transactions:
In order to import transactions like cost-sharing, proceeds-sharing etc properly, we have to consider that some accounts may have been excluded from the transaction. We have to detect whether the next row in the CSV is of type 9 (exception) resp. how many of the following rows are of type 9, then read their account id and exclude the account from the participating accounts field of the transaction.
I don't know what this line means: "for index,row in enumerate(reader):"
what about the comma between index and row, what does it mean?
How do we access the next row(s)?

**Comment by twothreenine** [comment]
Perhaps I can handle this by myself.
I vaguely understood the enumerate line now.

**Comment by Zepp10x** [comment]
I am looking into it now.

**Comment by twothreenine** [comment]
I don't know why but it is working now.
After changing a few things, various share transactions were imported correctly!
